<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="store" nsURI="https://riseclipse.github.io/ocl/example/model/store"
    nsPrefix="store">
  <eClassifiers xsi:type="ecore:EClass" name="Store">
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" ordered="false"
        upperBound="-1" eType="#//Product" unsettable="true" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artists" ordered="false"
        upperBound="-1" eType="#//Person" unsettable="true" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book" eSuperTypes="#//Product">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageCount" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" ordered="false"
        eType="#//Person" unsettable="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CD" eSuperTypes="#//Product">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trackCount" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singer" ordered="false"
        eType="#//Person" unsettable="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
