# *************************************************************************
# **  See https://fbricon.github.io/posts/use-github-releases-as-p2-repo/
# **
# **  This file is part of the RiseClipse tool
# **
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Release on GitHub as Eclipse p2 update site

on: workflow_dispatch

jobs:
  build:
    # Use a specific version to avoid unattended changes with latest
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v6
      with:
        path: ${{ github.event.repository.name }}

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'oracle'
        java-version: '21'
        cache: 'maven'

    - name: Build with Maven
      #run: |
      #  cd ${{ github.event.repository.name }}
      #  xvfb-run mvn -f releng/org.eclipse.ocl.releng.tycho/pom.xml -DGOAL=verify -DJAVADOC= -DPDFDOC= -DBUILD_TYPE=nightly -DBRANCH_NAME=origin/riseclipse/master -DBUILD_TYPE=nightly --show-version clean verify -Pnightly
      run: |
        cd ${{ github.event.repository.name }}
        xvfb-run mvn -f releng/org.eclipse.ocl.releng.tycho/pom.xml -DGOAL=verify -DJAVADOC= -DPDFDOC= -DBUILD_TYPE=nightly -DBRANCH_NAME=origin/3-add-a-workflow-to-deploy-on-github-as-a-p2-update-sit -DBUILD_TYPE=nightly --show-version clean verify -Pnightly

    - name: Upload flat p2 update site
      #if: github.ref == 'refs/heads/riseclipse/master'
      if: github.ref == 'refs/heads/3-add-a-workflow-to-deploy-on-github-as-a-p2-update-site'
      uses: crowbarmaster/GH-Automatic-Releases@latest
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly build"
        files: |
          ${{ github.event.repository.name }}/releng/org.eclipse.ocl.releng.build-site/target/flat-repository/*
