# *************************************************************************
# **  See https://fbricon.github.io/posts/use-github-releases-as-p2-repo/
# **  And https://github.com/riseclipse/riseclipse-distribution/blob/master/.github/workflows/Deploy-As-P2-Update-Site.yml
# *************************************************************************

name: Release as Eclipse p2 update site

on: workflow_dispatch

jobs:
  build:
    # Use a specific version to avoid unattended changes with latest
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Build with Maven
      run: |
        cd ${{ github.event.repository.name }}
        mvn --batch-mode verify
