name: Verify tests

on:
  push

jobs:
  build:
    # Use a specific version to avoid unattended changes with latest
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'
        cache: 'maven'

    # && mvn -f releng/org.eclipse.ocl.releng.tycho/pom.xml -DBUILD_TYPE=nightly -Pnightly clean verify
    - name: Build with Maven
      run: |
        cd ${{ github.event.repository.name }}
        xvfb-run mvn --version
