name: Verify tests

on:
  push

jobs:
  build:
    # Use a specific version to avoid unattended changes with latest
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'
        cache: 'maven'

    - name: Build with Maven
      run: |
        cd ${{ github.event.repository.name }}
        xvfb-run mvn -f releng/org.eclipse.ocl.releng.tycho/pom.xml -DGOAL=verify -DJAVADOC= -DPDFDOC= -DBUILD_TYPE=nightly -DBRANCH_NAME=origin/feat/mathlib-stdlib-6.23 -DBUILD_TYPE=nightly --show-version clean verify -Pnightly

    - name: Upload flat p2 update site
      if: github.ref == 'refs/heads/feat/mathlib-stdlib-6.23'
      uses: crowbarmaster/GH-Automatic-Releases@latest
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly build"
        files: |
          ${{ github.event.repository.name }}/releng/org.eclipse.ocl.releng.build-site/target/flat-repository/*
