name: Verify tests

on: workflow_dispatch

jobs:
  build:
    # Use a specific version to avoid unattended changes with latest
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'
        cache: 'maven'

    - name: Install Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    #- name: Install Eclipse
    #    run: |
    #      ECLIPSE_VERSION=$(curl -sL https://download.eclipse.org/technology/epp/downloads/release/release.xml | grep -oP '(?<=<present>).*?(?=/R</present>)')
    #      eclipsetgz="eclipse-java-${ECLIPSE_VERSION}-R-linux-gtk-x86_64.tar.gz"
    #      curl --remote-name "{ECLIPSE_DOWNLOADS}/${ECLIPSE_VERSION}/R"
    #      tar zxf ${eclipsetgz} && rm ${eclipsetgz}

    - name: Build with Maven
      run: |
        cd ${{ github.event.repository.name }}
        xvfb-run mvn -f releng/org.eclipse.ocl.releng.tycho/pom.xml -DBUILD_TYPE=nightly -Pnightly clean verify
